### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [anagolob3141/Projekt-za-Financni-prektikum#1]
@anagolob3141, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Constrained-clustering-via-diagrams`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

**Comment by anagolob3141** [comment]
Sedaj je popravljeno, hvala.
